before:
  hooks:
    - go mod download  
builds:
  - 
    main: ./cmd/killgrave/main.go
    ldflags: 
      - -s -w -X main._version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
archives:
  - 
    replacements:    
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip    
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
brew:
  name: killgrave
  github:
    owner: friendsofgo
    name: homebrew-tap    
  folder: Formula  
  description: |
    Simple way to generate fake servers
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true
