builds:
  - 
    main: ./cmd/killgrave/main.go
    ldflags: 
      - -s -w -X github.com/friendsofgo/killgrave/internal/app/cmd._version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - freebsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
archives:
  -
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip    
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
brews:
  -
    name: killgrave
    tap:
      owner: friendsofgo
      name: homebrew-tap
      token: "{{ .Env.GH_RELEASER }}"
    folder: Formula
    description: |
      Simple way to generate fake servers
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true
