version: 2.1
commands:
  install-sys-deps:
    description: "It installs the system dependencies required to run the pipelines"
    steps:
      - run: sudo apt-get install libxml2-dev
jobs:
  build-go1_15:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/friendsofgo/killgrave
    steps:
      - install-sys-deps
      - checkout
      - run: go test -v -race ./...
      - run: go build -race cmd/killgrave/main.go
  build-go1_16:
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/src/github.com/friendsofgo/killgrave
    steps:
      - install-sys-deps
      - checkout
      - run: go test -v -race ./...
      - run: go build -race cmd/killgrave/main.go
  build-go_latest:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/friendsofgo/killgrave
    steps:
      - install-sys-deps
      - checkout
      - run: go test -v -race ./...
      - run: go build -race cmd/killgrave/main.go      
  coverage:  
    docker:
      - image: circleci/golang:latest
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/friendsofgo/killgrave
    steps:
      - install-sys-deps
      - checkout
      - run: make coverage      
      - run: bash <(curl -s https://codecov.io/bash)
  release:
    docker:
      - image: circleci/golang:latest
        environment:
          GO111MODULE: "on"
    steps:
     - install-sys-deps
     - checkout
     - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-go1_15
      - build-go1_16
      - build-go_latest
      - coverage
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
