version: 2.1
jobs:
  build-go1_11_6:
    docker:
      - image: circleci/golang:1.11.6
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go test -v -race ./...
      - run: go build -race cmd/killgrave/main.go
  build-go1_12_1:
    docker:
      - image: circleci/golang:1.12.1
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go test -v -race ./...
      - run: go build -race cmd/killgrave/main.go  
  build-go_latest:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go test -v -race ./...
      - run: go build -race cmd/killgrave/main.go      
  coverage:  
    docker:
      - image: circleci/golang:latest
    steps:
      - run: make coverage      
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-go1_11_6
      - build-go1_12_1
      - build-go_latest
      - coverage
